#common:
#    resource: "@CommonBundle/Controller/"
#    type:     annotation
#    prefix:   /

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /app
        permanent: true

app:
    resource: '@AppBundle/Controller/'
    type: annotation
