# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        CommonBundle\Entity\User: sha512

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        member:
            entity:
                class: CommonBundle\Entity\User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        app:
#            pattern: ^/app
#            anonymous: true
#            guard:
#                authenticators:
#                    - CommonBundle\Security\Guard\FormLoginAuthenticator
#            provider:  member
#            logout:
#                path: /app/logout
#                target: /app/login

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

#    access_control:
#        - { path: ^/app/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/app, roles: ROLE_MEMBER }