services:
#    common.example:
#        class: CommonBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    CommonBundle\EventListener\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    common.security.guard.form_login:
        class: CommonBundle\Security\Guard\FormLoginAuthenticator
        arguments: ['@service_container']